name: Deploy dispatch rules to GAE

on:
  push:
    branches:
      - main
    paths:
      - "dispatch.yaml"

  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: ENV variable
        options:
          - d1
          - q1
jobs:
  deploy:
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      environment: ${{ github.event.inputs.environment }}

  deploy-dispatch:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Deploy dispatch.yaml to GAE
        run: yarn deploy:dispatch ${{ needs.deploy.outputs.ENV }}
