name: Deploy frontend service to GAE

on:
  push:
    branches:
      - main
    paths:
      - "services/frontend/**"
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      environment: ${{ github.event.inputs.environment }}

  deploy-frontend:
    if: github.event.head_commit.message != 'skip frontend' && contains(github.event.commits.*.modified, 'services/frontend/**')
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Install frontend dependencies
        run: yarn install:frontend

      - name: Setup frontend
        run: yarn setup:frontend ${{ needs.deploy.outputs.ENV }}

      - name: Deploy frontend to GAE
        run: yarn deploy:frontend ${{ needs.deploy.outputs.ENV }}
