name: Deploy backend service to GAE

on:
  push:
    branches:
      - main
    paths:
      - "services/backend/**"
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
jobs:
  deploy:
    uses: ./.github/workflows/reusable-jobs.yml
    with:
      environment: ${{ github.event.inputs.environment }}

  deploy-backend:
    if: github.event.head_commit.message != 'skip backend' && contains(github.event.commits.*.modified, 'services/backend/**')
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Install backend dependencies
        run: yarn install:backend

      - name: Setup backend
        run: yarn setup:backend ${{ needs.deploy.outputs.ENV }}

      - name: Deploy backend to GAE
        run: yarn deploy:backend ${{ needs.deploy.outputs.ENV }}
