name: Reusable common job for deploying to GAE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Set branch-based environment variables on PR merged
        if: ${{ github.event_name == 'pull_request' }}
        uses: iamtheyammer/branch-env-vars@v1.2.2
        with:
          bevOverwrite: true
          ENV: |
            !pr>main:d1
            !default:d1

      - name: "Override branch-based environment if run from workflow_dispatch"
        if: ${{ github.event_name == 'workflow_dispatch'}}
        run: |
          echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: Check ENV
        id: set-env
        run: echo "::set-output name=ENV::$ENV"
          echo "Environment variable for environment - $environment"

      - name: "Set up Google Cloud Auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
        env:
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: Install root dependencies
        run: yarn install

      - name: Fetch secrets
        run: yarn secrets:fetch $ENV
